#!/usr/bin/env bash
set -euo pipefail

: "${NEXUS_MIGRATE_PASSWORD:?NEXUS_MIGRATE_PASSWORD is required}"
: "${NEXUS_APP_PASSWORD:?NEXUS_APP_PASSWORD is required}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nexus_migrator') THEN
    CREATE ROLE nexus_migrator LOGIN PASSWORD '${NEXUS_MIGRATE_PASSWORD}'
      NOSUPERUSER NOCREATEDB NOCREATEROLE BYPASSRLS;
  ELSE
    ALTER ROLE nexus_migrator WITH LOGIN PASSWORD '${NEXUS_MIGRATE_PASSWORD}' BYPASSRLS;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nexus_app') THEN
    CREATE ROLE nexus_app LOGIN PASSWORD '${NEXUS_APP_PASSWORD}'
      NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
  ELSE
    ALTER ROLE nexus_app WITH LOGIN PASSWORD '${NEXUS_APP_PASSWORD}' NOBYPASSRLS;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nexus_cron') THEN
    CREATE ROLE nexus_cron NOLOGIN
      NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
  END IF;
END
\$\$;
EOSQL
